apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-ni4c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-ni4c
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-ni4c
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: private-quarkus-devfile-sample-ni4c
status:
  loadBalancer: {}
